"""empty message

Revision ID: 797d96881e6e
Revises: None
Create Date: 2017-07-10 12:26:14.383799

"""

# revision identifiers, used by Alembic.
revision = '797d96881e6e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wikis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wikis')
    # ### end Alembic commands ###
