"""empty message

Revision ID: 862f4eabb5fa
Revises: e2b202b425ca
Create Date: 2017-07-17 16:04:18.370048

"""

# revision identifiers, used by Alembic.
revision = '862f4eabb5fa'
down_revision = 'e2b202b425ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wiki_category',
    sa.Column('wiki_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['wiki_id'], ['wiki.id'], )
    )
    op.drop_column(u'draft_category', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'draft_category', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_table('wiki_category')
    # ### end Alembic commands ###
