"""empty message

Revision ID: e2b202b425ca
Revises: e6f27fb90769
Create Date: 2017-07-17 10:08:19.893425

"""

# revision identifiers, used by Alembic.
revision = 'e2b202b425ca'
down_revision = 'e6f27fb90769'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_category',
    sa.Column('draft_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['draft_id'], ['draft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'category', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'category', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column(u'category', 'owner_id')
    op.drop_table('draft_category')
    # ### end Alembic commands ###
