"""empty message

Revision ID: e6f27fb90769
Revises: 797d96881e6e
Create Date: 2017-07-11 11:17:23.518344

"""

# revision identifiers, used by Alembic.
revision = 'e6f27fb90769'
down_revision = '797d96881e6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.create_table('draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.UnicodeText(), nullable=False),
    sa.Column('answer', sa.UnicodeText(), nullable=False),
    sa.Column('ts_created', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wiki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.UnicodeText(), nullable=False),
    sa.Column('answer', sa.UnicodeText(), nullable=False),
    sa.Column('ts_published', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('wikis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wikis',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'wikis_pkey')
    )
    op.drop_table('wiki')
    op.drop_table('draft')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
